version: '3.8'
services:
  tornabra-api:
    container_name: tornabra-api
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - tornabra-db
    networks:
      - database-network

  tornabra-db:
    image: 'bitnami/postgresql'
    container_name: tornabra-db
    environment:
      - POSTGRESQL_USERNAME=tornabra
      - POSTGRESQL_PASSWORD=tornabra
      - POSTGRESQL_DATABASE=tornabradb
    ports:
      - 5432:5432
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      - database-network

volumes:
  postgresql_data:
    driver: local

networks:
  database-network:
